<?php



/* Custom Single.php for project only view */

global $post, $doctype;



?>

<!DOCTYPE html>

<html <?php language_attributes( $doctype ); ?>>

<head>

    <meta charset="utf-8">

    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <?php $client = get_field('client'); ?>

    <title><?php the_title(); ?> | <?php echo esc_html($client); ?></title>



    <meta name="viewport" content="width=device-width, initial-scale=1.0">



    <?php if(get_field('hide_from_search_engines',$post->ID)): ?>

        <meta name="robots" content="noindex, nofollow">

    <?php endif; ?>



    <?php // wp_head(); Removed for visual consistency 
           wp_enqueue_style('psp-custom', PSP_PLUGINURI . '/css/psp-custom.css.php', [], null);

            // Enqueue JS
            // wp_enqueue_script('psp-jquery', PSP_PLUGINURI . '/js/jquery.js', [], '1.2.5', true);
            wp_enqueue_script('psp-frontend-lib', PSP_PLUGINURI . '/js/psp-frontend-lib.min.js', ['jquery'], '1.2.5', true);
            wp_enqueue_script('psp-frontend-behavior', PSP_PLUGINURI . '/js/psp-frontend-behavior.js', ['jquery'], '1.2.5', true);

            // Localize Ajax URL
            wp_localize_script('psp-frontend-behavior', 'MyAjax', ['ajaxurl' => admin_url('admin-ajax.php')]);

            wp_enqueue_script('html5shiv', PSP_PLUGINURI . '/js/html5shiv.min.js', [], null, false);
            wp_script_add_data('html5shiv', 'conditional', 'lte IE 9');

            wp_enqueue_script('css3-mediaqueries', PSP_PLUGINURI . '/js/css3-mediaqueries.js', [], null, false);
            wp_script_add_data('css3-mediaqueries', 'conditional', 'lte IE 9');

            wp_enqueue_style('ie-styles', PSP_PLUGINURI . '/css/ie.css', [], null);
            wp_style_add_data('ie-styles', 'conditional', 'IE');
    ?>


    <?php do_action('psppan_head'); ?>



</head>

<body class="psp-standalone-page">



    <div id="psp-projects" class="psp-standard-template">



        <?php do_action('psppan_the_header'); ?>



        <div id="overview" class="psp-comments-wrapper">



			<?php if( (get_option('psp_logo') != '' ) && (get_option('psp_logo') != 'http://') ): ?>

				<div class="psp-login-logo">

					<img src="<?php echo esc_url(get_option('psp_logo')); ?>">

				</div>

            <?php endif; ?>



            <div id="psp-login">

                <?php if( !post_password_required() ): ?>



                    <h2><?php esc_html_e('This Project Requires a Login','psp_projects'); ?></h2>



                    <?php

                    if( !is_user_logged_in() ):

                        panorama_login_form();

                    else:

                        echo '<p>' . esc_html_e( 'You don\'t have permission to access this project', 'psp_projects' ) . '</p>';

                    endif; ?>



                <?php endif; ?>



                <?php

                if( post_password_required() && !current_user_can('publish_psp_projects') ): ?>



                    <h2><?php esc_html_e('This Project is Password Protected test','psp_projects'); ?></h2>



                    <?php echo get_the_password_form(); //phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- only safe HTML output generated by this function. ?>



                <?php endif; ?>



            </div> <!--/#psp-login-->

        </div> <!--/#overview-->

    </div> <!--/#psp-project-->



    <?php wp_footer(); ?>



</body>

</html>

